### ISSUE TITLE
Support axum 0.8.0

### ISSUE THREAD

**Issue by sondrelg** [cloudwalk/axum-test-helper#31]
Hi @renancloudwalk. Thanks for creating this, it's been really nice to use 👌 

Just wanted to let you know, the axum 0.8.0 release seems to require an update:

```rust
error[E0308]: mismatched types
   --> src/foo.rs:180:38
    |
180 |         let client = TestClient::new(app).await;
    |                      --------------- ^^^ expected `axum::routing::Router`, found `Router`
    |                      |
    |                      arguments to this function are incorrect
```

Do you think you'll have time to publish a compatibility fix?

**Comment by sawmurai** [comment]
In case anyone is interested in how a migration away from `TestClient` looks like:

`get_app().await` returns a `Router` (it also has state that is created async, hence the `.await`) 

Works with axum 0.8.1.

```diff
     #[tokio::test]
     async fn returns_list_of_exercises() {
-        let client = TestClient::new(get_app().await).await;
+        let mut app = get_app().await;
+        let cookie = login_coach(&mut app).await;
 
-        let cookie = login_coach(&client).await;
-        let res = client
-            .get("/exercise")
+        let req = Request::builder()
+            .method("GET")
+            .uri("/exercise")
             .header("cookie", &cookie)
-            .send()
-            .await;
+            .body(Body::empty())
+            .unwrap();
+
+        let res = app.oneshot(req).await.unwrap();
         assert_eq!(res.status(), StatusCode::OK);
 
         let expected = r#"[{"id":"88dc900e-82c1-11ed-93b1-cfc2854f95b8","name":"Deadlift","groupId":null,"active":true,"userId":"d9ae8e47-112f-4d37-ba20-0cb1dbc776b6","metricType":"weight","usedCount":0,"offset":0}]"#;
-        assert_eq!(res.text().await, expected);
+        let body = axum::body::to_bytes(res.into_body(), 1000000)
+            .await
+            .unwrap();
+        assert_eq!(std::str::from_utf8(&body).unwrap(), expected);
     }
```

**Comment by BrainBlasted** [comment]
Popping in for anyone else looking for a solution: [axum-test](https://github.com/JosephLenton/axum-test) is a similar crate with a similarly easy to use API that supports Axum 0.8.0.
